export enum RESPONSE_STATUS_CODES {
  SUCCESS = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export const STATUS_MESSAGES = {
  [RESPONSE_STATUS_CODES.SUCCESS]: "OK",
  [RESPONSE_STATUS_CODES.CREATED]: "Created",
  [RESPONSE_STATUS_CODES.NO_CONTENT]: "No Content",
  [RESPONSE_STATUS_CODES.BAD_REQUEST]: "Bad Request",
  [RESPONSE_STATUS_CODES.NOT_FOUND]: "Not Found",
  [RESPONSE_STATUS_CODES.INTERNAL_SERVER_ERROR]: "Internal Server Error",
};

export enum USERS_DB_ERRORS_MAP {
  BAD_REQUEST = RESPONSE_STATUS_CODES.BAD_REQUEST,
  NOT_FOUND = RESPONSE_STATUS_CODES.NOT_FOUND,
  INTERNAL = RESPONSE_STATUS_CODES.INTERNAL_SERVER_ERROR,
}
